[versions]
androidx-room = "2.8.5"
circuit = "0.38.0"
kotlin = "2.4.20"
metro = "1.4.3"

[plugins]
android-application = { id = "com.android.application", version = "9.4.0" }
android-library = { id = "com.android.library", version = "9.4.0" }
convention-android-application = { id = "convention-android-application" }
convention-android-library = { id = "convention-android-library" }
convention-jvm-library = { id = "convention-jvm-library" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.3.11" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }

[libraries]
android-desugarJdkLibs = "com.android.tools:desugar_jdk_libs:2.1.5"
androidx-activity-compose = "androidx.activity:activity-compose:1.13.0"
androidx-compose-foundation = "androidx.compose.foundation:foundation:1.12.0"
androidx-compose-material-icons-extended = "androidx.compose.material:material-icons-extended:1.7.8"
androidx-compose-material3 = "androidx.compose.material3:material3:1.5.0-alpha27"
androidx-compose-runtime = "androidx.compose.runtime:runtime:1.12.0"
androidx-compose-ui = "androidx.compose.ui:ui:1.12.0"
androidx-core = "androidx.core:core:1.19.0"
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
circuit-foundation = { module = "com.slack.circuit:circuit-foundation", version.ref = "circuit" }
circuit-runtime = { module = "com.slack.circuit:circuit-runtime", version.ref = "circuit" }
circuit-serialization = { module = "com.slack.circuit:circuit-serialization", version.ref = "circuit" }
google-material = "com.google.android.material:material:1.14.0"
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1"
metrox-android = { module = "dev.zacsweers.metro:metrox-android", version.ref = "metro" }
